name: feature CI

on:
  workflow_dispatch:
  push:
    branches:
      - feature/*
    paths-ignore: 
      - 'README'
      - 'README.md'
      - 'LICENSE'
      - '.github/**'

run-name: v${{ github.run_number }}-r${{ github.run_attempt }}

jobs:
  build_and_test:
    name: build_and_test
    runs-on: ${{ vars.DEFAULT_RUNS_ON }}

    steps:
      - uses: btungut/devops/.github/actions/common@master
        id: common

        
      - uses: btungut/devops/.github/actions/git-checkout@master
        with:
          gitToken: ${{ secrets.GITHUB_TOKEN }}

      
      - uses: ./app/.github/actions/dotnet-common
        with:
          dir-sln: app
          dir-src-project: app/src
          dir-unit-tests: app/tests
          dir-integration-tests: app/tests_integration
