name: release stable

on:
  # workflow_run: 
  #   workflows: ["release candidate"]
  #   types:
  #     - completed
  workflow_dispatch:
    inputs:
      RC_RUN_ID:
        description: 'Run ID for the release candidate'
        required: true

run-name: release for ${{ inputs.RC_RUN_ID }}

jobs:
  main:
      
    name: main
    runs-on: ${{ vars.DEFAULT_RUNS_ON }}
    env:
      DW_PATH: ${{ github.workspace }}/.tmp/download

    steps:
      - uses: btungut/devops/.github/actions/common@master
        id: common


      - name: iteration_vars
        id: iteration_vars
        shell: bash
        run: |
          set -euo pipefail

          rm -rf $DW_PATH
          mkdir -p $DW_PATH

          RC_RUN_ID="${{ inputs.RC_RUN_ID }}"
          if [ -z "$RC_RUN_ID" ]; then
              echo "inputs.RC_RUN_ID is null or empty whitespace!"
              exit 1
          fi
          echo "RC_RUN_ID=$RC_RUN_ID" >> $GITHUB_ENV
          echo "RC_RUN_ID=$RC_RUN_ID"         

          BRANCH_VERSION="${{ steps.common.outputs.branch-version }}"
          if [ -z "$BRANCH_VERSION" ]; then
              echo "steps.common.outputs.branch-version is null or empty whitespace!"
              exit 1
          fi

          echo "RC_RUN_ID: $RC_RUN_ID"
          echo "BRANCH_VERSION: $BRANCH_VERSION"


      - name: download_artifacts
        id: download_artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: 'NuGet*'
          github-token: ${{ secrets.GH_TOKEN }}
          run-id: ${{ inputs.RC_RUN_ID }}
          path: ${{ env.DW_PATH }}
          repository: ${{ github.repository }}
          merge-multiple: false


      - name: buro
        shell: bash
        run: |
          set -euo pipefail
          echo "PWD = $(pwd)"

          DW_PATH="${{ env.DW_PATH }}"
          [ -z "$DW_PATH" ] && { echo "DW_PATH is null or empty whitespace!"; exit 1; }
          [ ! -d "$DW_PATH" ] && { echo "DW_PATH does not exist!"; exit 1; }
          
          pushd $DW_PATH
          ls -al
          [ -z "$(ls -A)" ] && { echo "DW_PATH is empty! PLEASE CHECK YOUR INPUTS!!!"; exit 1; }
          

          echo "bekliyore..."
          sleep 120s
        

      # - name: create_release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: ${{ steps.iteration_vars.outputs.BRANCH_VERSION }}
      #     release_name: ${{ steps.iteration_vars.outputs.BRANCH_VERSION }}
      #     body: |
      #       Release candidate run ID: ${{ steps.iteration_vars.outputs.RC_RUN_ID }}
      #     draft: false
      #     prerelease: false
      #     token: ${{ secrets.GITHUB_TOKEN }}